# Generated by Django 5.0.4 on 2024-04-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurploModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('quantity', models.TextField()),
                ('price', models.FloatField()),
                ('expired', models.BooleanField()),
            ],
        ),
    ]
